---
# 项目信息
site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.full_name }}
site_description: {{ cookiecutter.project_short_description }}

# Github信息
repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug.replace('_', '-') }} 
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug.replace('_', '-') }}
edit_uri: ""

# 版权
copyright: 版权 &copy; 2021 {{ cookiecutter.full_name }}

# 配置
theme:
  name: shadocs
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: cn

# 页脚
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}
      name: {{ cookiecutter.github_username }} on GitHub

# 导航
nav:
  - 首页: index.md
  - 版本: version.md
