---
# Project Information
site_name: {{ cookiecutter.project_name }}
site_author: {{ cookiecutter.full_name }}
site_description: {{ cookiecutter.project_short_description }}

# Repository information
repo_name: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug.replace('_', '-') }}
repo_url: https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.project_slug.replace('_', '-') }}
edit_uri: ""

# Copyright
copyright: 版权 &copy; 2021 {{ cookiecutter.full_name }}

# Configuration
theme:
  name: shadocs
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
  language: cn

# Footer
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/{{ cookiecutter.github_username }}
      name: {{ cookiecutter.github_username }} on GitHub

# Page tree
nav:
  - 首页: index.md
